# Generated by Django 3.1.4 on 2021-01-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realproject', '0004_catefgory_pcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catefgory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='realproject.Category'),
        ),
    ]
